In [2]:
import numpy as np

In [3]:
def softmax(x):
    """
    x: a matrix or vector
    
    outputs: softmaxed version of x
    
    recall the softmax for element i is e^x_i / sum_j e^x_j
    
    softmax is invariant if you change the whole vector by constant c
    common practice is to subtract max(vector) = c from the vector
    """
    orig_shape = x.shape

    
    # Matrix
    if len(x.shape) > 1:
        x_max = np.max(x, axis=1)
        x = x - x_max[:,None]
        x_exp = np.exp(x)
        x_rowsum = np.sum(x_exp, axis=1)
        x = x_exp / x_rowsum[:,None]
    # Vector
    else:
        x_max = np.max(x)
        x = x - x_max
        x_exp = np.exp(x)
        x_sum = np.sum(x_exp)
        x = x_exp / x_sum

    assert x.shape == orig_shape
    return x

In [9]:
x1 = np.array([1,2,3])
x2 = np.array([
    [1,2,3],
    [1,4,9],
    [1,8,27],
])

print(softmax(x1))


print(softmax(x2))

[ 0.09003057  0.24472847  0.66524096]
[[  9.00305732e-02   2.44728471e-01   6.65240956e-01]
 [  3.33106430e-04   6.69062149e-03   9.92976272e-01]
 [  5.10908900e-12   5.60279641e-09   9.99999994e-01]]


In [10]:
def logistic(x):
    """
    x: a vector or matrix
    outputs: logistic for each element in x
    
    Common activation function
    
    Recall that the logistic activation function is given by
    1 / (1 + e^-x)
    """
    
    orig_shape = x.shape

    # Matrix
    if len(x.shape) > 1:
        x = 1 / (1 + np.exp(-x))
    # Vector
    else:
        x = 1 / (1 + np.exp(-x))
    assert x.shape == orig_shape
    return x

In [15]:
print(logistic(x1))
print(logistic(x2))

[ 0.73105858  0.88079708  0.95257413]
[[ 0.73105858  0.88079708  0.95257413]
 [ 0.73105858  0.98201379  0.99987661]
 [ 0.73105858  0.99966465  1.        ]]
